---
# Install MariaDB on the destination server
- include_tasks: mariadb.yml

# Allow remote connections to database server
- include_tasks: mariadb-remote.yml
  when: db_remote_connections == "allow"
